# Generated by Django 4.2.1 on 2023-05-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finca',
        ),
    ]
